version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "3002:3002"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - order-service
